import NextAuth from 'next-auth';
import GoogleProvider from 'next-auth/providers/google';
import AppleProvider from 'next-auth/providers/apple';
import dbConnect from '@/lib/mongodb';
import User from '@/models/User';

console.log('NextAuth configuration loading...', {
  googleClientIdExists: !!process.env.GOOGLE_CLIENT_ID,
  appleIdExists: !!process.env.APPLE_ID,
  appleSecretExists: !!process.env.APPLE_SECRET,
  nextAuthUrl: process.env.NEXTAUTH_URL || '(not set)',
  nodeEnv: process.env.NODE_ENV,
});

export const authOptions = {
  providers: [
    GoogleProvider({
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      authorization: {
        params: {
          scope: 'openid email profile',
        },
      },
    }),
    AppleProvider({
      clientId: process.env.APPLE_ID,
      clientSecret: process.env.APPLE_SECRET,
      wellKnown: 'https://appleid.apple.com/.well-known/openid-configuration',
      authorization: {
        params: {
          scope: 'name email',
          response_mode: 'form_post',
          state: undefined, // Ensure state is generated by NextAuth
        },
      },
      checks: ['state'],
      profile(profile) {
        console.log('Apple profile received:', {
          sub: profile.sub,
          email: profile.email,
          name: profile.name,
        });
        return {
          id: profile.sub,
          email: profile.email,
          name: profile.name
            ? `${profile.name.firstName || ''} ${profile.name.lastName || ''}`.trim()
            : null,
        };
      },
    }),
  ],
  pages: {
    signIn: '/auth/signin',
    error: '/auth/error',
  },
  cookies: {
    sessionToken: {
      name: `next-auth.session-token`,
      options: {
        httpOnly: true,
        sameSite: 'lax',
        path: '/',
        secure: process.env.NODE_ENV === 'production',
        maxAge: 30 * 24 * 60 * 60, // 30 days
      },
    },
    callbackUrl: {
      name: `next-auth.callback-url`,
      options: {
        httpOnly: true,
        sameSite: 'lax',
        path: '/',
        secure: process.env.NODE_ENV === 'production',
        maxAge: 15 * 60, // 15 minutes
      },
    },
    csrfToken: {
      name: `next-auth.csrf-token`,
      options: {
        httpOnly: true,
        sameSite: 'lax',
        path: '/',
        secure: process.env.NODE_ENV === 'production',
        maxAge: 15 * 60,
      },
    },
    state: {
      name: `next-auth.state`,
      options: {
        httpOnly: true,
        sameSite: 'lax',
        path: '/',
        secure: process.env.NODE_ENV === 'production',
        maxAge: 15 * 60, // 15 minutes
        domain: process.env.NODE_ENV === 'production' ? '.fliday.com' : 'localhost',
      },
    },
  },
  callbacks: {
    async session({ session, token }) {
      if (token.sub) {
        session.user.id = token.sub;
      }
      if (token.role) {
        session.user.role = token.role;
      }
      return session;
    },
    async jwt({ token, account, user, profile }) {
      if (account) {
        console.log(`JWT callback for ${account.provider} sign-in`, {
          providerId: account.providerAccountId,
          hasEmail: !!user?.email,
          hasName: !!user?.name,
        });
        token.provider = account.provider;
        token.providerId = account.providerAccountId;
        if (account.provider === 'apple' && profile) {
          token.name = user.name;
        }
      }
      if (user?.id && !token.role) {
        try {
          token.role = user.role || 'user';
        } catch (error) {
          console.error('Error setting user role in token:', error.message);
        }
      }
      return token;
    },
    async signIn({ user, account, profile }) {
      console.log(`Sign-in attempt with ${account.provider}`, {
        email: user.email,
        providerId: account.providerAccountId,
      });
      if (!user.email) {
        console.error('User email missing from OAuth provider');
        return false;
      }
      try {
        await dbConnect();
        console.log('Database connected successfully');
        const existingUser = await User.findOne({ email: user.email })
          .select('_id role provider providerId name')
          .lean();
        if (existingUser) {
          console.log(`Found existing user with email: ${user.email}`);
          user.id = existingUser._id.toString();
          user.role = existingUser.role || 'user';
          const updateData = {
            lastLogin: new Date(),
            provider: account.provider,
            providerId: account.providerAccountId,
          };
          if (user.name && user.name.trim() !== '') {
            updateData.name = user.name;
          }
          User.findByIdAndUpdate(existingUser._id, { $set: updateData }, { new: false })
            .catch(err => console.error('Background user update failed:', err));
        } else {
          console.log(`Creating new user with email: ${user.email}`);
          const newUser = await User.create({
            name: user.name || 'Unnamed User',
            email: user.email,
            provider: account.provider,
            providerId: account.providerAccountId,
            role: 'user',
            lastLogin: new Date(),
          });
          user.id = newUser._id.toString();
          user.role = 'user';
          console.log(`New user created with ID: ${user.id}`);
        }
        return true;
      } catch (error) {
        console.error('Error in signIn callback:', error.message);
        return true;
      }
    },
    async redirect({ url, baseUrl }) {
      console.log('Redirect callback:', { url, baseUrl });
      if (url.startsWith('/') || url.startsWith(baseUrl)) {
        return url;
      }
      return baseUrl;
    },
  },
  events: {
    async signIn({ user }) {
      console.log(`User signed in: ${user.email}`);
    },
    async signOut({ token }) {
      console.log(`User signed out: ${token?.sub || 'Unknown user'}`);
    },
    async createUser({ user }) {
      console.log(`User created: ${user.email}`);
    },
    async linkAccount({ user, account }) {
      console.log(`Account linked: ${account.provider} for ${user.email}`);
    },
    async error(message) {
      console.error('Auth error occurred:', message);
    },
  },
  logger: {
    error(code, metadata) {
      console.error(`[AUTH ERROR] ${code}:`, metadata);
      if (code === 'oauth_callback_error') {
        console.error('OAuth callback error details:', {
          provider: metadata?.providerId,
          error: metadata?.error?.message,
          stack: metadata?.error?.stack?.split('\n').slice(0, 3).join('\n'),
        });
      }
    },
    warn(code) {
      console.warn(`[AUTH WARNING] ${code}`);
    },
    debug(code, metadata) {
      if (process.env.NEXTAUTH_DEBUG === 'true') {
        console.log(`[AUTH DEBUG] ${code}:`, metadata);
      }
    },
  },
  secret: process.env.NEXTAUTH_SECRET,
  session: {
    strategy: 'jwt',
    maxAge: 30 * 24 * 60 * 60,
  },
  debug: process.env.NODE_ENV !== 'production' || process.env.NEXTAUTH_DEBUG === 'true',
  jwt: {
    maxAge: 30 * 24 * 60 * 60,
  },
};

const handler = NextAuth(authOptions);

export { handler as GET, handler as POST };

export const config = {
  runtime: 'nodejs',
};